# Generated by Django 4.2.7 on 2026-01-28 05:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='Номер аудитории')),
                ('capacity', models.IntegerField(default=30, verbose_name='Вместимость')),
                ('equipment', models.TextField(blank=True, verbose_name='Оборудование')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Аудитория',
                'verbose_name_plural': 'Аудитории',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=50, verbose_name='Номер аудитории')),
                ('weekday', models.IntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], verbose_name='День недели')),
                ('start_time', models.TimeField(default=datetime.time(8, 0), verbose_name='Начало работы')),
                ('end_time', models.TimeField(default=datetime.time(20, 0), verbose_name='Конец работы')),
                ('is_working', models.BooleanField(default=True, verbose_name='Рабочий день')),
            ],
            options={
                'verbose_name': 'Рабочие часы',
                'verbose_name_plural': 'Рабочие часы',
                'unique_together': {('room_number', 'weekday')},
            },
        ),
        migrations.CreateModel(
            name='RoomSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=50, verbose_name='Номер аудитории')),
                ('booking_date', models.DateField(verbose_name='Дата бронирования')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('end_time', models.TimeField(verbose_name='Время окончания')),
                ('booking_type', models.CharField(choices=[('lesson', 'Занятие'), ('exam', 'Экзамен'), ('meeting', 'Собрание')], default='lesson', max_length=20, verbose_name='Тип бронирования')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('booked_by', models.EmailField(max_length=254, verbose_name='Забронировал')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Расписание аудитории',
                'verbose_name_plural': 'Расписание аудиторий',
                'ordering': ['booking_date', 'start_time'],
                'indexes': [models.Index(fields=['room_number', 'booking_date'], name='availabilit_room_nu_4ced9e_idx')],
            },
        ),
    ]
